In [1]:
import pandas as pd
import numpy as np

In [4]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print("a1:\n", a1)
print("a2:\n", a2)
print("a1 + a2:\n", a1 + a2)
print("a1 - a2:\n", a2 - a1)
print("a1 * a2:\n", a1 * a2)
print("a1 / a2:\n", a2 / a1)
print("transpose of a1:\n", a1.transpose())
print("transpose of a2:\n", a2.T)

a1:
 [[1 1]
 [2 2]]
a2:
 [[3 3]
 [4 4]]
a1 + a2:
 [[4 4]
 [6 6]]
a1 - a2:
 [[2 2]
 [2 2]]
a1 * a2:
 [[3 3]
 [8 8]]
a1 / a2:
 [[3. 3.]
 [2. 2.]]
transpose of a1:
 [[1 2]
 [1 2]]
transpose of a2:
 [[3 4]
 [3 4]]
